apiVersion: dataservices.nutanix.com/v1alpha1
kind: Application
metadata:
  name: pacman-app
  namespace: pacman
spec:
  applicationSelector:
    resourceLabelSelectors:
      - includeResources:
        - group: apps
          kind: Deployment
        - group: ""
          kind: Service
        - group: "apps"
          kind: PersistentVolume
        - group: ""
          kind: PersistentVolumeClaim

